language: ruby

dist: trusty

matrix:
  include:
    - rvm: 2.7.6
      gemfile: gemfiles/rails.5.2.gemfile
    - rvm: 2.7.6
      gemfile: gemfiles/rails.5.2.gemfile
      env: USE_MYSQL=true

    - rvm: 2.7.6
      gemfile: gemfiles/rails.6.0.gemfile
    - rvm: 2.7.6
      gemfile: gemfiles/rails.6.0.gemfile
      env: USE_MYSQL=true

    - rvm: 2.7.6
      gemfile: gemfiles/rails.6.1.gemfile
    - rvm: 2.7.6
      gemfile: gemfiles/rails.6.1.gemfile
      env: USE_MYSQL=true
    - rvm: 3.0.4
      gemfile: gemfiles/rails.6.1.gemfile
    - rvm: 3.0.4
      gemfile: gemfiles/rails6.1.gemfile
      env: USE_MYSQL=true
    - rvm: 3.1.2
      gemfile: gemfiles/rails.6.1.gemfile
    - rvm: 3.1.2
      gemfile: gemfiles/rails.6.1.gemfile
      env: USE_MYSQL=true

    - rvm: 3.1.2
      gemfile: gemfiles/rails.7.0.gemfile
      env: USE_MYSQL=true
    - rvm: 3.1.2
      gemfile: gemfiles/rails.7.0.gemfile

services:
  - mysql

before_install:
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

git:
  depth: 1
